server:
    address: localhost
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC
        username: root
        password: sondmfemfdj000~!
        driver-class-name: com.mysql.cj.jdbc.Driver